version: '3.3'

services:
  backend:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile-back
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

  front:
    build: 
     context: ./frontend
     dockerfile: Dockerfile-front
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
