version: '3.8'

services:
  db:
    restart: always
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=fast
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kanikim@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    restart: unless-stopped

  backend:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile-back
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build: 
     context: ./frontend
     dockerfile: Dockerfile-front
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
volumes:
  postgres_data:
